-- cet ordre ou le suivant g?n?re 
 -- une erreur en fonction du renommage 
 -- effectif ou pas de la table BIB_DetailsEmprunts

/***
DROP TABLE BIB_DetailsEmprunts;
DROP TABLE BIB_Details;

DROP TABLE BIB_Exemplaires;
DROP TABLE BIB_Ouvrages;
DROP TABLE BIB_Genres;
DROP TABLE BIB_Emprunts;
DROP TABLE BIB_Membres;
***/

CREATE TABLE BIB_Genres (
  code      CHAR(5)      CONSTRAINT PK_genres PRIMARY KEY, -- NOT NULL car clef primaire
  libelle   VARCHAR2(80) CONSTRAINT NN_libelle NOT NULL
) ;

-- BIB_Ouvrages
CREATE TABLE BIB_Ouvrages (
  isbn      NUMBER(10)      CONSTRAINT PK_BIB_Ouvrages PRIMARY KEY,
  titre     VARCHAR2(200)   CONSTRAINT NN_titre NOT NULL,   
  auteur    VARCHAR2(80)    NULL,  
  genre     CHAR(5)         CONSTRAINT FK_BIB_Genres REFERENCES BIB_Genres(code),
  editeur   VARCHAR2(80)    NULL
);

CREATE TABLE BIB_Exemplaires(
  isbn      NUMBER(10),  -- NOT NULL car participe ? la clef primaire
  numero    NUMBER(3)    GENERATED BY DEFAULT AS IDENTITY, -- NOT NULL car participe ? la clef primaire
  etat      CHAR(5)      CONSTRAINT NN_etat NOT NULL,
  CONSTRAINT PK_exemplaires PRIMARY KEY(isbn, numero),
  CONSTRAINT FK_exemplaires_ouvrages FOREIGN KEY(isbn) REFERENCES BIB_Ouvrages(isbn),
  CONSTRAINT CK_exemplaires_etat CHECK (etat IN('NE','BO','MO','MA'))
);

CREATE TABLE BIB_Membres(
  numero    NUMBER(6)    GENERATED BY DEFAULT AS IDENTITY  
                         CONSTRAINT PK_membres PRIMARY KEY,
  nom       VARCHAR2(80) NOT NULL,
  prenom    VARCHAR2(80) CONSTRAINT NN_prenom NOT NULL,
  adresse   VARCHAR2(200)CONSTRAINT NN_adresse NOT NULL,
  telephone CHAR(10)     CONSTRAINT NN_telephone NOT NULL,
  adhesion  DATE         CONSTRAINT NN_adhesion NOT NULL,
  duree     NUMBER(2)    CONSTRAINT NN_duree NOT NULL,
  CONSTRAINT CK_membres_duree CHECK (duree >= 0)
);

CREATE TABLE BIB_Emprunts(
  numero NUMBER(10) GENERATED BY DEFAULT AS IDENTITY
                    CONSTRAINT PK_emprunts PRIMARY KEY,
  membre NUMBER(6)  CONSTRAINT FK_emprunts_membres REFERENCES BIB_Membres(numero),
  creele DATE       DEFAULT SYSDATE
);

CREATE TABLE  BIB_DetailsEmprunts(
  emprunt   NUMBER(10) CONSTRAINT FK_details_emprunts REFERENCES BIB_Emprunts(numero),
  numero    NUMBER(3),
  isbn      NUMBER(10),
  exemplaire NUMBER(3),
  rendule   DATE,
  CONSTRAINT PK_detailsemprunts PRIMARY KEY (emprunt, numero),
  CONSTRAINT FK_detailsemprunts_exemplaires FOREIGN KEY(isbn, exemplaire) REFERENCES BIB_Exemplaires(isbn, numero)
);



